services:
  express_postgre:
    container_name: express_postgre_container
    image: flytask-node-app:1.0.0
    build: flytaskexpress/.
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
      image: postgres
      restart: always
      ports:
        - "5435:5435"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=flytask
  
