version: '3.1'

services:
  java_app:
    container_name: flytask_spring
    image: flytask-java-app:1.0.0
    build: flytask/.
    ports:
      - "8080:8080"
    depends_on:
      - db  

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
