services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_container"
    ports:
      - 80:80
    depends_on:
      - java_app
      - arquitecturas_integrales
      - django_postgre
      - express_postgre
    volumes:
    - ./nginx:/etc/nginx/conf.d

  arquitecturas_integrales:
    image: arquitecturas_integrales:1.0.0
    build: arquitecturas_integrales/.
    container_name: arquitecturas_integrales_container
    ports:
      - 5173:5173

  java_app:
    container_name: spring_postgre_container
    image: flytask-java-app:1.0.0
    build: flytask/.
    ports:
      - 8080:8080
    depends_on:
      - db   

  django_postgre:
    container_name: django_postgre_container
    image: flytask-python-app:1.0.0
    build: flytaskpyenv/flytaskpy/.
    ports:
      - 8000:8000
    depends_on:
      - db

  express_postgre:
    container_name: express_postgre_container
    image: flytask-node-app:1.0.0
    build: flytaskexpress/.
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flytask

  
