# Generated by Django 4.2.12 on 2024-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='usr_id',
        ),
    ]
