# Generated by Django 4.2.12 on 2024-05-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_task_usr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='usr_id',
            new_name='usr',
        ),
    ]
