# Generated by Django 4.1.13 on 2024-06-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Tasks',
        ),
    ]
