# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Environment variables to configure PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=flytask

# Add the SQL script to the Docker image
COPY create_schema.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432